### ISSUE TITLE
Broken images on "DOCS" page

### ISSUE THREAD

**Issue by timothydilbert** [KaotoIO/kaoto.io#22] opened 2023-03-21 21:00 UTC
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/79225033/226739636-6342c771-0ab6-4a07-9902-51d73d96dcd8.png">

**Comment by apupier** [comment] 2023-03-22 08:35
duplicate of #19

**Closed by apupier** 2023-03-22 08:35 UTC
